### ISSUE TITLE
Review Decaf's paper to figure out the Edwards points treatment & Compression.

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/Corretto#5]
In order to understand the Edwards points treatment and conversion into FieldElements and further conversions to Ristretto Scalars, read the [Decaf Paper](https://eprint.iacr.org/2015/673.pdf)

With this, we will start the Edwards Point compression implementation and further conversions.
This may also give us some light about the whole process in order to avoid EC point operations for Ristretto Scalar's equivalent ones.

**Comment by Bounce23** [comment]
Paper has been reviewed over the past two days. The next thing to add to an internal road map is following the `Montgomery batch` inversion trick and quotient groups. After thoroughly understanding the use of quotient groups to compress cofactor, the follow up is to understand the concepts behind the formation of the Ristretto field.

**Comment by Bounce23** [comment]
Building on this issue, it is now understood how the ristretto255 field uses wrapper functions on Edwards points to create equivalence in the Ristretto Scalar Field.

**Comment by Bounce23** [comment]
The `Ristretto` research, specifically surround the ristretto255, was undertaken following a combing of the` Decaf` paper to understand the best manner to progress through the new underlined roadmap. The most important thing that has been taken from this is defined in issue `#8`, where @CPerezz and I have defined the algorithm for using the embedment in the scalar field.

From this explanation, we can say our work on understanding `Decaf`/`Ristretto` and their techniques has consolidated our next step and this issue can therefore be closed.
